name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - run: nuget restore CSHelloWorld.sln
      - uses: microsoft/setup-msbuild@v1
      - run: |
          ./Dump-MSBuildProperties.ps1
        condition: true
      - run: msbuild CSHelloWorld.sln -property:Configuration=Release
        condition: false
